ADAM/ADAM/urls.py
# urls.py (ADAM)
# !/usr/bin/env python3
# coding=utf-8
# ruiz-mercado.gerardo@epa.gov

"""
ADAM URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/

Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns: path('blog/', include('blog.urls')).
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('main/ajax/getdata', views.getdata, name='getdata'),
    path('main/ajax/getbounds', views.getbounds, name='getbounds'),
    path('support', views.support, name='support'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('demo', views.demo, name='demo'),
    path('demo/eg1', views.demo_eg1, name='demo_eg1'),
    path('demo/eg2', views.demo_eg2, name='demo_eg2'),
    path('ajax/begintosolveeg2', views.beginsolveeg2, name='begintosolveeg2'),
    path('eg2_results/<id>', views.eg2_results, name='eg2_results'),
    # Module paths:
    # path('demo/', include('demo.urls')),
    path('expert/', include('expert.urls')),
    path('accounts/', include('accounts.urls')),
    path('teams/', include('teams.urls')),
    path('support/', include('support.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ADAM/support/urls.py
# urls.py (support)
# !/usr/bin/env python3
# coding=utf-8
# ruiz-mercado.gerardo@epa.gov
# pylint: skip-file
# We disable the invalid name because urlpatterns is the Django default

"""Add docstring."""  # TODO add docstring.

from django.urls import re_path
from .views import *
from support.views import *

app_name = 'support'

urlpatterns = [
    re_path(r'^$', index),
    re_path(r'^index/$', index, name='go_to_support'),

    re_path(r'^documentation/$', UserManualView.as_view(), name="documentation"),
    re_path(r'^download_manual/$', download_manual, name="download_manual"),
    re_path(r'events/', EventsView.as_view(), name='events'),
    re_path(r'references/', ReferencesView.as_view(), name='references'),

    re_path(r'^files/(?P<file_name>.+)', event_file_download, name='event_file_download'),

    re_path(r'^create/(?P<support_type_name>\w+)/$', SuggestionCreateView.as_view(), name='create_support'),
    re_path(r'^edit/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$', SuggestionEditView.as_view(), name='edit_support'),
    re_path(r'^delete/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$', delete_support, name='delete_support'),
    re_path(r'^list/(?P<support_type_name>\w+)/$', list_supports, name='list_supports'),
    re_path(r'^search/$', search_support, name='search_support'),
    re_path(r'^search/result/$', result_search_support, name='result_search_support'),
    re_path(r'^show/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$', show_support, name='show_support'),

    # new
    re_path(r'^file/upload/(?P<obj_id>\d+)/$', file_upload_support, name='file_upload_support'),
    re_path(r'^support_attachment/delete/(?P<obj_id>\d+)/$', delete_support_attachment, name='delete_support_attachment'),

    re_path(r'^type/create/$', create_support_type, name='create_support_type'),
    re_path(r'^type/edit/(?P<obj_id>\d+)/$', edit_support_type, name='edit_support_type'),
    re_path(r'^type/delete/(?P<obj_id>\d+)/$', delete_support_type, name='delete_support_type'),
    re_path(r'^type/list/$', list_support_types, name='list_support_types'),
    re_path(r'^type/search/$', search_support_type, name='search_support_type'),
    re_path(r'^type/search/result/$', result_search_support_type, name='result_search_support_type'),
    re_path(r'^type/show/(?P<obj_id>\d+)/$', show_support_type, name='show_support_type'),

    re_path(r'^priority/create/$', create_priority, name='create_priority'),
    re_path(r'^priority/edit/(?P<obj_id>\d+)/$', edit_priority, name='edit_priority'),
    re_path(r'^priority/delete/(?P<obj_id>\d+)/$', delete_priority, name='delete_priority'),
    re_path(r'^priority/list/$', list_priorities, name='list_priorities'),
    re_path(r'^priority/search/$', search_priority, name='search_priority'),
    re_path(r'^priority/search/result/$', result_search_priority, name='result_search_priority'),
    re_path(r'^priority/show/(?P<obj_id>\d+)/$', show_priority, name='show_priority'),

    re_path(r'^support/search/result/thirty/$', search_support_for_last_30, name='search_support_for_last_30'),
    re_path(r'^support/search/result/sixty/$', search_support_for_last_60, name='search_support_for_last_60'),
    re_path(r'^support/search/result/ninety/$', search_support_for_last_90, name='search_support_for_last_90'),
    re_path(r'^support/search/result/one_eighty/$', search_support_for_last_180, name='search_support_for_last_180'),
]

ADAM/support/views.py
# views.py (support)
# !/usr/bin/env python3
# coding=utf-8
# ruiz-mercado.gerardo@epa.gov
# pylint: skip-file

"""
Views for managing user support functions.

Available functions:
- Create support ticket.
- Save changes to support form.
"""

from decimal import getcontext
from datetime import datetime, timedelta
from math import *
from os.path import join

from constants.models import *
from constants.utils import *
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic import FormView, TemplateView

from ADAM.settings import MANUAL_NAME, DOWNLOADS_DIR
from .forms import *
from .models import *

getcontext().prec = 9


class UserManualView(TemplateView):
    """
    View to present and process the 'request more info' form.

    :param request:
    :return:
    """

    # form_class = InformationRequestForm

    def get(self, request, *args, **kwargs):
        """Present the request info form."""
        # form = self.form_class()
        # return render(request, 'main/manual.html', {'form': form})
        return render(request, 'main/manual.html', {})


class EventsView(TemplateView):
    """Support Upcoming Events view."""

    def get(self, request, *args, **kwargs):
        """
        :param request:.

        :param args:
        :param kwargs:
        :return:
        """
        return render(request, 'main/events.html', {})


class ReferencesView(TemplateView):
    """Support site References view."""

    def get(self, request, *args, **kwargs):
        """
        :param request:.

        :param args:
        :param kwargs:
        :return:
        """
        return render(request, 'main/references.html', {})


@login_required
def download_manual(request):
    """Download the user manual."""
    return download_file(request, MANUAL_NAME)


def event_file_download(request, *args, **kwargs):
    """Find and download the file matching the provided file name."""
    file_name = kwargs.get('file_name', None)
    return download_file(request, file_name)


def download_file(request, name):
    """Receives the path, name, extension of a file to be returned to user."""
    name_split = name.split('.')
    ext = name_split[len(name_split) - 1]
    file = join(DOWNLOADS_DIR, name)

    if ext == 'docx' or ext == 'pdf' or 'ppt' in ext:
        with open(file, 'rb') as doc:
            response = HttpResponse(doc)
            con_disp = 'attachment; filename="' + name + '"'
            response['Content-Disposition'] = con_disp
            return response

    # elif ext == 'docx':
    #    with open(file, 'rb') as doc:
    #        response = HttpResponse(doc)
    #        con_disp = 'attachment; filename='' + name + """
    #        response['Content-Disposition'] = con_disp
    #        return response

    elif 'xls' in ext:
        with open(file, 'rb') as xls:
            con_type = 'application/vnd.vnd.openxmlformats-officedocument.' + \
                'spreadsheetml.sheet'
            response = HttpResponse(xls, con_type)
            con_disp = 'attachment; filename="' + name + '"'
            response['Content-Disposition'] = con_disp
            return response

    return HttpResponse()


@login_required
def index(request):
    """User login support."""
    user = request.user
    title = 'Support Main Page'

    return render(request, 'main/support.html', locals())


# Start Support


class SuggestionCreateView(FormView):
    """View to create a new support ticket."""

    form_class = SupportForm
    template = 'main/create_support.html'

    @method_decorator(login_required)
    def get(self, request, support_type_name):
        """Display the project create form."""
        if 'suggestion' == support_type_name.lower():
            title = 'Make a suggestion to improve ADAM'
            instructions = 'Describe your suggestion for ADAM below.  ' + \
                'You will have the option to add attachments ' + \
                'after saving the suggestion.'
        else:
            title = 'request help with ADAM'
            instructions = 'Describe the problem you encountered with ' + \
                'ADAM below.  You will have the option to add ' + \
                'attachments after saving the request.'
        form = self.form_class(initial={'weblink': request.user.email})
        return render(request, self.template, locals())

    @method_decorator(login_required)
    def post(self, request, support_type_name, *args, **kwargs):
        """Save the changes to the support form."""
        user = request.user
        form = self.form_class(data=request.POST, files=request.FILES)

        if form.is_valid():

            support = form.save(commit=False)
            support.user = user
            support.created_by = user
            support.last_modified_by = user
            # lookup ticket type
            support.support_type = SupportType.objects.filter(
                the_name__iexact=support_type_name).first()
            support.save()

            url = reverse('support:edit_support',
                          kwargs={'support_type_name': support_type_name,
                                  'obj_id': support.id}) + '?new=1'
            return HttpResponseRedirect(url)
        else:
            return render(request, self.template, locals())


class SuggestionEditView(FormView):
    """View to create a new support ticket."""

    form_class = SupportForm
    admin_form_class = SupportAdminForm
    template = 'edit/edit_support.html'
    no_edit_template = 'main/no_edit.html'

    @method_decorator(login_required)
    def get(self, request, support_type_name, obj_id):
        """Add docstring."""  # TODO add docstring.
        user = request.user
        form_class = SupportForm if not user.is_staff else SupportAdminForm
        support = get_object_or_404(Support, id=obj_id)
        support_attachments = SupportAttachment.objects.filter(support=support)

        title = 'Suggestion' if support_type_name == 'suggestion' else 'Help'
        instructions = 'Edit your request or add attachments below.'
        if request.GET.get('new') is not None:
            warn = 'You\'re almost done. Update your suggestion as ' + \
                'needed, add attachments, and then click Submit ' + \
                'to complete your request'

        # make sure the user has permission to edit this support object
        if not user.is_staff and support.user != user:
            return render(request, self.no_edit_template, locals())

        form = form_class(instance=support)
        return render(request, self.template, locals())

    @method_decorator(login_required)
    def post(self, request, support_type_name, obj_id, *args, **kwargs):
        """Save changes to user form."""
        user = request.user
        title = 'Suggestion' if support_type_name == 'suggestion' else 'Help'
        instructions = 'Edit your request or add attachments below.'
        form_class = SupportForm if not user.is_staff else SupportAdminForm
        support = get_object_or_404(Support, id=obj_id)
        support_attachments = SupportAttachment.objects.filter(support=support)

        # make sure the user has permission to edit this support object
        if not user.is_staff and support.user != user:
            return render(request, self.no_edit_template, locals())

        form = form_class(data=request.POST, files=request.FILES)
        if form.is_valid():

            support.modified = request.user
            support.subject = form.cleaned_data['subject']
            support.the_description = form.cleaned_data['the_description']
            support.weblink = form.cleaned_data['weblink']
            if user.is_staff:
                support.date_resolved = form.cleaned_data['date_resolved']
                support.review_notes = form.cleaned_data['review_notes']

            support.save()

            # reload the attachment list
            support_attachments = SupportAttachment.objects.filter(
                support=support)

            # email the DataSearch admins and cc the user
            # get type of ticket
            if support.support_type is not None:
                support_type_desc = support.support_type.the_name
            else:
                support_type_desc = support_type_name

            support_email = settings.SUPPORT_EMAIL
            submitter_email = support.weblink

            # Use this when testing so ordqatrack@epa.gov
            # doesn't get test emails.
            # email_to = [submitter_email]
            email_to = [support_email, submitter_email]

            # detect if this is a new request versus editing
            # if it's an update, we add language to the subject and
            # body to indicate that to the recipient.
            referer_url = request.META['HTTP_REFERER']
            if referer_url.endswith('?new=1'):
                email_subject = 'ADAM ' + str(support_type_desc) + ' ' + \
                    str(obj_id) + ': ' + str(support.subject)
                email_body = support.the_description
            else:
                email_subject = 'UPDATED: ADAM ' + str(support_type_desc) + \
                    ' ' + str(obj_id) + ': ' + str(support.subject)
                email_body = 'This automated email is to notify you ' + \
                    'that your support request has been updated.\r\n\r\n' + \
                    'Description:\r\n' + str(support.the_description) + \
                    '\r\n\r\nDate Resolved: ' + str(support.date_resolved) + \
                    '\r\n\r\nReview Notes:\r\n' + str(support.review_notes)

            the_email = create_qt_email_message(

ADAM/support/templates/edit/edit_support.html
{% extends "base/site_base_support.html" %}
{% block support_content %}
{% load static %}

    <script>
        $(function () {
            var ul=$('#upload ul');
            // Change this to the location of your server-side upload handler:
            var url='/support/file/upload/{{support.id}}/';

            $('#drop a').click(function(){
                // Simulate a click on the file input button to show the file browser dialog
                $(this).parent().find('input').click();
            });

            // Initialize the jQuery File Upload plugin
            $('#upload').fileupload({
                // This element will accept file drag/drop uploading
                dropZone: $('#drop'),

                // This function is called when a file is added to the queue;
                // either via the browse button, or via drag/drop:
                add: function (e, data) {
                    var tpl=$('<li class="working"><input type="text" value="0" data-width="48" data-height="48"' +
                    ' data-fgColor="#0788a5" data-readOnly="1" data-bgColor="#3e4043" /><p></p><span></span></li>');

                    // Append the file name and file size
                    tpl.find('p').text(data.files[0].name)
                            .append('<i>' + formatFileSize(data.files[0].size) + '</i>');

                    // Add the HTML to the UL element
                    data.context=tpl.appendTo(ul);

                    // Initialize the knob plugin
                    tpl.find('input').knob();

                    // Listen for clicks on the cancel icon
                    tpl.find('span').click(function(){
                        if(tpl.hasClass('working')){
                            jqXHR.abort();
                        }
                        tpl.fadeOut(function(){
                            tpl.remove();
                        });
                    });
                    // Automatically upload the file once it is added to the queue
                    var jqXHR=data.submit();
                },

                progress: function(e, data){
                    // Calculate the completion percentage of the upload
                    var progress=parseInt(data.loaded / data.total * 100, 10);
                    // Update the hidden input field and trigger a change
                    // so that the jQuery knob plugin knows to update the dial
                    data.context.find('input').val(progress).change();
                    if(progress == 100){
                        data.context.removeClass('working');
                    }
                },

                fail:function(e, data){
                    // Something has gone wrong!
                    data.context.addClass('error');
                }
            });

            // Prevent the default action when a file is dropped on the window
            $(document).on('drop dragover', function (e) {
                e.preventDefault();
            });

            // Helper function that formats the file sizes
            function formatFileSize(bytes) {
                if (typeof bytes !== 'number') {
                    return '';
                }
                if (bytes >= 1000000000) {
                    return (bytes / 1000000000).toFixed(2) + ' GB';
                }
                if (bytes >= 1000000) {
                    return (bytes / 1000000).toFixed(2) + ' MB';
                }
                return (bytes / 1000).toFixed(2) + ' KB';
            }
        });
    </script>

    <h3>{{title}} #{{support.id}}</h3>
    <div class="text-muted vmargin20">
        {{instructions}}
    </div>

    <form class="form-horizontal" enctype="multipart/form-data" method="post" action="." role="form" novalidate>
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger">
            <h5>Please correct the following errors</h5>
            {% for field in form %}
            {% if field.errors %}
                <div>{{field.label_tag}} {{ field.errors|striptags }}</div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        {% if success %}
        <div class="alert alert-success">
            {{success}} <span class="glyphicon glyphicon-ok"></span>
        </div>
        {% endif %}

        {% if warn %}
        <div class="alert alert-warning">
            {{warn}}
        </div>
        {% endif %}

        {% for field in form %}
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <div>{{field.label_tag}}</div>
                <div class="help-block">{{field.help_text}}</div>
            </label>
            <div class="col-sm-10">
                {{field}}
                {% if field.errors %}<div class="alert alert-danger">{{field.errors.as_text}}</div>{% endif %}
            </div>

        </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-2"></div>
            <div class="col-sm-10">
                <input type="submit" value="Submit" class="btn btn-success">
                Add Any Attachments Before Submitting
            </div>
        </div>
    </form>

    <script>
        $(".chosen-select").chosen({});
        $(".date-control").datepicker({ dateFormat: "yy-mm-dd" });
    </script>

    {% if support_attachments %}
        <br>
        <p><h3>File Attachments</h3></p>

        <table class="example table-autosort table-stripeclass:alternate table-autofilter" id="support_attachments_table">
            <thead id="support_attachments_head">
            <tr>
                <th class="table-sortable:alphanumeric">Filename</th>
                <th class="table-header">Delete</th>
            </tr>
            <tr>
                <th class="table-filterable"></th>
                <th class="table-header"></th>
            </tr>

            </thead>
            <tbody id="support_attachments_body">
                {% for obj in support_attachments %}
                    <tr>
                        <td class='filename_td'><a href="{{MEDIA_URL}}{{obj.attachment|urlencode}}">{{obj.the_name}}</a></td>
                        <td><a href="{% url 'support:delete_support_attachment' obj.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}

    <div>
        {% if support.id %}
        <form id="upload" method="post"action={% url 'support:file_upload_support' support.id %} enctype="multipart/form-data">
            {% csrf_token %}
            <div id="drop">
                Drop Files ONLY Here
                <a>Browse</a>
                <input type="file" name="upl" multiple />
            </div>
            <ul><!-- The file uploads will be shown here --></ul>
        </form>
        {% endif %}
    </div>

    <script>
        $(".date-control").datepicker({ dateFormat: "yy-mm-dd" });
    </script>

{% endblock %}