ADAM/ADAM/urls.py
# urls.py (ADAM)
# !/usr/bin/env python3
# coding=utf-8
# ruiz-mercado.gerardo@epa.gov

"""
ADAM URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/

Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns: path('blog/', include('blog.urls')).
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('main/ajax/getdata', views.getdata, name='getdata'),
    path('main/ajax/getbounds', views.getbounds, name='getbounds'),
    path('support', views.support, name='support'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('demo', views.demo, name='demo'),
    path('demo/eg1', views.demo_eg1, name='demo_eg1'),
    path('demo/eg2', views.demo_eg2, name='demo_eg2'),
    path('ajax/begintosolveeg2', views.beginsolveeg2, name='begintosolveeg2'),
    path('eg2_results/<id>', views.eg2_results, name='eg2_results'),
    # Module paths:
    # path('demo/', include('demo.urls')),
    path('expert/', include('expert.urls')),
    path('accounts/', include('accounts.urls')),
    path('teams/', include('teams.urls')),
    path('support/', include('support.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ADAM/support/urls.py
# urls.py (support)
# !/usr/bin/env python3
# coding=utf-8
# ruiz-mercado.gerardo@epa.gov
# pylint: skip-file
# We disable the invalid name because urlpatterns is the Django default

"""Add docstring."""  # TODO add docstring.

from django.urls import re_path
from .views import *
from support.views import *

app_name = 'support'

urlpatterns = [
    re_path(r'^$', index),
    re_path(r'^index/$', index, name='go_to_support'),

    re_path(r'^documentation/$', UserManualView.as_view(), name="documentation"),
    re_path(r'^download_manual/$', download_manual, name="download_manual"),
    re_path(r'events/', EventsView.as_view(), name='events'),
    re_path(r'references/', ReferencesView.as_view(), name='references'),

    re_path(r'^files/(?P<file_name>.+)', event_file_download, name='event_file_download'),

    re_path(r'^create/(?P<support_type_name>\w+)/$', SuggestionCreateView.as_view(), name='create_support'),
    re_path(r'^edit/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$', SuggestionEditView.as_view(), name='edit_support'),
    re_path(r'^delete/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$', delete_support, name='delete_support'),
    re_path(r'^list/(?P<support_type_name>\w+)/$', list_supports, name='list_supports'),
    re_path(r'^search/$', search_support, name='search_support'),
    re_path(r'^search/result/$', result_search_support, name='result_search_support'),
    re_path(r'^show/(?P<support_type_name>\w+)/(?P<obj_id>\d+)/$', show_support, name='show_support'),

    # new
    re_path(r'^file/upload/(?P<obj_id>\d+)/$', file_upload_support, name='file_upload_support'),
    re_path(r'^support_attachment/delete/(?P<obj_id>\d+)/$', delete_support_attachment, name='delete_support_attachment'),

    re_path(r'^type/create/$', create_support_type, name='create_support_type'),
    re_path(r'^type/edit/(?P<obj_id>\d+)/$', edit_support_type, name='edit_support_type'),
    re_path(r'^type/delete/(?P<obj_id>\d+)/$', delete_support_type, name='delete_support_type'),
    re_path(r'^type/list/$', list_support_types, name='list_support_types'),
    re_path(r'^type/search/$', search_support_type, name='search_support_type'),
    re_path(r'^type/search/result/$', result_search_support_type, name='result_search_support_type'),
    re_path(r'^type/show/(?P<obj_id>\d+)/$', show_support_type, name='show_support_type'),

    re_path(r'^priority/create/$', create_priority, name='create_priority'),
    re_path(r'^priority/edit/(?P<obj_id>\d+)/$', edit_priority, name='edit_priority'),
    re_path(r'^priority/delete/(?P<obj_id>\d+)/$', delete_priority, name='delete_priority'),
    re_path(r'^priority/list/$', list_priorities, name='list_priorities'),
    re_path(r'^priority/search/$', search_priority, name='search_priority'),
    re_path(r'^priority/search/result/$', result_search_priority, name='result_search_priority'),
    re_path(r'^priority/show/(?P<obj_id>\d+)/$', show_priority, name='show_priority'),

    re_path(r'^support/search/result/thirty/$', search_support_for_last_30, name='search_support_for_last_30'),
    re_path(r'^support/search/result/sixty/$', search_support_for_last_60, name='search_support_for_last_60'),
    re_path(r'^support/search/result/ninety/$', search_support_for_last_90, name='search_support_for_last_90'),
    re_path(r'^support/search/result/one_eighty/$', search_support_for_last_180, name='search_support_for_last_180'),
]

ADAM/main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse, FileResponse
from django.conf import settings
from django.forms import formset_factory
from django.utils.encoding import smart_str
from wsgiref.util import FileWrapper
from django.db.models import Q
from functools import reduce
from .models import *
from .forms import *
from .tasks import *
from math import log
from collections import namedtuple
import string
import random
import os
import io
import csv
import zipfile
import json
import operator

from .util import *


# Create your views here.

"""Main page - login/out, Register"""
# registered page - redirect to usermain
def exp_registered(request):
    return render(request, 'exp_registered.html')

# register page
def exp_register(request):
    fail = 0
    if (request.POST.get('user_register')):
        uf = UserForm(request.POST)
        if uf.is_valid():
            new_user = User.objects.create_user(username = uf.cleaned_data['username'],password = uf.cleaned_data['password'])
            new_user.first_name = uf.cleaned_data['first_name']
            new_user.last_name = uf.cleaned_data['last_name']
            new_user.email = uf.cleaned_data['email']
            new_user.save()
            new_info = UserInfo(user = new_user)
            new_info.organization = uf.cleaned_data['organization']
            new_info.save()
            new_base = UserDatabase(user = new_user)
            new_base.save()
            for p in Product.objects.all():
                if p.public:
                    newitem = UserHasProd(userdatabase = new_base, product = p)
                    newitem.save()
            for t in Technology.objects.all():
                if t.public:
                    newitem = UserHasTech(userdatabase = new_base, technology = t)
                    newitem.save()
            new_base.save()
            return redirect(reverse('main:exp_registered'))
        else:
            fail = 1
            context = {'userform': uf, 'fail':fail}
            return render(request, 'exp_register.html', context)
    else:
        uf = UserForm()
        context = {'userform': uf, 'fail':fail}
        return render(request, 'exp_register.html', context)

# login page
def exp_login(request):
    formfail = 0
    authfail = 0
    if (request.POST.get('user_login')):
        uf = LoginForm(request.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            user = authenticate(username = username, password = password)
            if user is None:
                authfail = 1
                context = {'loginform': uf, 'formfail':formfail, 'authfail': authfail}
                return render(request, 'exp_login.html', context)
            else:
                login(request,user)
                base = user.userdatabase
                for p in Product.objects.all():
                    if p.public and p not in base.prods.all():
                        newitem = UserHasProd(userdatabase = base, product = p)
                        newitem.save()
                for t in Technology.objects.all():
                    if t.public and t not in base.techs.all():
                        newitem = UserHasTech(userdatabase = base, technology = t)
                        newitem.save()
                base.save()
                return redirect('main:exp_usermain')
        else:
            formfail = 1
            context = {'loginform': uf, 'formfail':formfail, 'authfail': authfail}
            return render(request, 'exp_login.html', context)
    else:
        uf = LoginForm()
        context = {'loginform': uf, 'formfail': formfail,  'authfail': authfail}
        return render(request,'exp_login.html', context)

# logout page, will redirect to expertmain
def exp_logout(request):
    user = request.user
    if user.is_authenticated:
        logout(request)
        return render(request, 'exp_logout.html')
    else:
        redirect('main:expertmain')

"""User Dashboard"""
# usermain page
@login_required()
def exp_usermain(request):
    user = request.user
    return render(request, 'exp_usermain.html', {'user': user})

@login_required()
def exp_advpanel(request):
    user = request.user
    return render(request, 'exp_advpanel.html', {'user': user})


"""Task List and Creation"""
@login_required()
def exp_task_list(request):
    user = request.user
    tasklist = user.opttask_set.all()
    casels = CaseGroup.objects.all()
    return render(request, 'exp_task_list.html', {'user': user, 'tasklist': tasklist, 'caselist': casels})

@login_required()
def taskmanagedelete(request):
    user = request.user
    success = False
    if (request.POST):
        post_data = request.POST
        type = post_data['type']
        task_id = post_data['task_id']
        if 'delete_task' in type:
            task = user.opttask_set.get(id = task_id)
            task.delete()
            success = True
        return JsonResponse({'success': success})
    else:
        return HttpResponse("Invalid request!")

@login_required()
def newmodel(request):
    user = request.user
    success = False
    if (request.POST):
        post_data = request.POST
        modelname = post_data['modelname']
        modelnotes = post_data['modelnotes'].replace("'"," ").replace('"',' ').replace('\n','')
        new_task = user.opttask_set.create(task_name = modelname, date_create = timezone.now(), task_pseudoid = id_generator(), notes=modelnotes)
        new_task.save()
        success = True
        return JsonResponse({'success': success})
    else:
        return HttpResponse("Invalid request!")

@login_required()
def copymodel(request):
    user = request.user
    success = False
    if (request.POST):
        post_data = request.POST
        modelname = post_data['modelname']
        modelnotes = post_data['modelnotes'].replace("'"," ").replace('"',' ').replace('\n','')
        task = user.opttask_set.create(task_name = modelname, date_create = timezone.now(), task_pseudoid = id_generator(), notes=modelnotes)

        load_id = post_data['loadid']
        if 'c' not in load_id:
            load = OptTask.objects.get(pk = int(load_id))
        else:
            load = CaseStudy.objects.get(pk = int(load_id[1:]))

        task.task_status = "Data Required"
        task.model_type  = load.model_type
        task.save()
        task.code_path = codeselector(task.model_type)

        if 'c' not in load_id:
            task.finished_steps = load.finished_steps.replace("5","").replace("6","")
        else:
            task.finished_steps = '1234'

        task.timeunit = load.timeunit
        task.supLatLs = load.supLatLs
        task.supLngLs = load.supLngLs
        task.supProLs = load.supProLs
        task.supCapLs = load.supCapLs
        task.supBidLs = load.supBidLs
        task.supNames = load.supNames
        # tech site data
        task.siteLatLs = load.siteLatLs
        task.siteLngLs = load.siteLngLs
        task.siteTecLs = load.siteTecLs
        task.siteCapLs = load.siteCapLs
        task.siteNames = load.siteNames
        # tech cand data
        task.candLatLs = load.candLatLs
        task.candLngLs = load.candLngLs
        task.candTecLs = load.candTecLs
        task.candNames = load.candNames
        # demand data
        task.demLatLs = load.demLatLs
        task.demLngLs = load.demLngLs
        task.demProLs = load.demProLs
        task.demCapLs = load.demCapLs
        task.demBidLs = load.demBidLs
        task.demNames = load.demNames

        task.save()
        success = True
        return JsonResponse({'success': success})
    else:
        return HttpResponse("Invalid request!")

"""Guidence for defining a problem"""
"""Step 1 - Model Type and Time Scope"""
@login_required()
def exp_task_step1(request, task_id):
    user = request.user
    task = OptTask.objects.get(pk = task_id)
    task_is_user = task in user.opttask_set.all()
    if not task_is_user:
        return redirect('main:exp_login')
    else:
        if (request.GET.get('confirm_type')):
            mf = TaskTypeForm(request.GET)
            if mf.is_valid():
                task.model_type = int(mf.cleaned_data['model_type'])
                task.code_path = codeselector(task.model_type)
                task.timeunit = timeselector(int(mf.cleaned_data['time_basis']))
                if '1' not in task.finished_steps:
                    task.finished_steps += '1'
                task.save()
            return redirect('main:exp_task_step2new', task.id)
        else:
            modelform = TaskTypeForm()
            return render(request, 'exp_task_step1.html', {'user': user, 'task': task, 'modelform':modelform})

"""Step 2 - Supply Data"""
@login_required()
def exp_task_step2new(request, task_id):
    user = request.user
    task = OptTask.objects.get(pk = task_id)
    task_is_user = task in user.opttask_set.all()
    if not task_is_user:
        return redirect('main:exp_login')
    else:
        uf = DataUploadForm()
        return render(request, 'exp_task_step2new.html', {'user': user, 'task': task, 'dataupload': uf})

@login_required()
def step2supfileselection(request):
    user = request.user
    if request.POST:
        data = request.POST
        supfileid = int(data['fileid'])
        file = DataDocument.objects.get(pk = supfileid)
        msg, supdata = readSupFile(user, file.docfile)
        return JsonResponse({'msg': msg, 'supdata':supdata})
    else:
        return HttpResponse("Invalid request!")

@login_required()
def step2suploadmodeldata(request):
    user = request.user
    if request.POST:
        data = request.POST
        loadid = int(data['loadid'])

ADAM/support/templates/main/create_help_request.html
{% extends "base/site_base_support.html" %}
{% block support_content %}

<h3>Enter request, save, add any attachments, submit</h3>

<form class="form-horizontal" enctype="multipart/form-data" method="post" action="." role="form" novalidate>

    {% csrf_token %}

    {% if form.errors %}
    <div class="alert alert-danger">
        <h5>Please correct the following errors</h5>
        {% for field in form %}
        {% if field.errors %}
        <div>{{field.label_tag}} {{ field.errors|striptags }}</div>
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    {% if success %}
    <div class="alert alert-success">
        The help request has been created. <span class="glyphicon glyphicon-ok"></span>
    </div>
    {% endif %}

    {% for field in form %}
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <div>{{field.label_tag}}</div>
            <div class="help-block">{{field.help_text}}</div>
        </label>
        <div class="col-sm-10">
            {{field}}
            {% if field.errors %}<div class="alert alert-danger">{{field.errors.as_text}}</div>{% endif %}
        </div>

    </div>
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-2"></div>
        <div class="col-sm-10">
            <input type="submit" value="Save" class="btn btn-success">
        </div>
    </div>
</form>

{% endblock %}

ADAM/support/templates/main/create_support.html
{% extends "base/site_base_support.html" %}
{% block support_content %}

<h3>{{title}}</h3>
<div class="text-muted vmargin20">
    {{instructions}}
</div>

<form class="form-horizontal " enctype="multipart/form-data" method="post" action="." role="form" novalidate>

    {% csrf_token %}

    {% if form.errors %}
    <div class="alert alert-danger">
        <h5>Please correct the following errors</h5>
        {% for field in form %}
        {% if field.errors %}
        <div>{{field.label_tag}} {{ field.errors|striptags }}</div>
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}

    {% for field in form %}
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <div>{{field.label_tag}}</div>
            <div class="help-block">{{field.help_text}}</div>
        </label>
        <div class="col-sm-10">
            {{field}}
            {% if field.errors %}<div class="alert alert-danger">{{field.errors.as_text}}</div>{% endif %}
        </div>

    </div>
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-2"></div>
        <div class="col-sm-10">
            <input type="submit" value="Save" class="btn btn-success">
        </div>
    </div>
</form>

{% endblock %}

ADAM/support/templates/main/email.html
<!DOCTYPE html>
<html lang="en">
<html>
    <head>
    </head>
    <body>
        <p>{{ user_name }}</p>
        <p>{{ subject }}</p>
    </body>
</html>

ADAM/support/templates/main/events.html
{% extends 'main/base.html' %}
{% block content %}
<div class="white-box">
    <div>
        <h2>Upcoming Events</h2>
        <h4>Check back often for upcoming events, presentations, training sessions, and more on the ADAM tool.</h4>
        <hr />
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 mt-3">
                    <div class="card">
                        <div class="card-horizontal">
                            <div class="img-square-wrapper card-horizontal-img col-2">
                                <!-- NOTE: Day of the week. -->
                                <div class="col-12">FRI</div>
                                <!-- NOTE: Month and date. -->
                                <div class="col-12">June 19</div>
                                <!-- NOTE: Year. -->
                                <div class="col-12">2020</div>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <!-- NOTE: This section is the bolded title in an event card. -->
                                    Microplastics Project ORD -- Microsoft Teams Meeting
                                </h4>
                                <p class="card-text">
                                    <!-- NOTE: This section is paragraph text in an event card's body. -->
                                    Meeting to discuss potential Region 10 participation for sampling events.
                                    <button class="btn btn-md btn-success float-right m-2"
                                            onclick="window.location.href='/support/files/K-LRTD-0032360-QP-1-1 Signed.pdf'">
                                        Download the QAPP
                                    </button>
                                </p>
                            </div>
                        </div>
                        <div class="card-footer">
                            <!-- NOTE: This section is used to document when this event card was last updated. -->
                            <small class="text-muted">Last updated 6/15/2020</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 mt-3">
                    <div class="card">
                        <div class="card-horizontal">
                            <div class="img-square-wrapper card-horizontal-img col-2">
                                <!-- NOTE: Day of the week. -->
                                <div class="col-12">MON</div>
                                <!-- NOTE: Month and date. -->
                                <div class="col-12">June 15</div>
                                <!-- NOTE: Year. -->
                                <div class="col-12">2020</div>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <!-- NOTE: This section is the bolded title in an event card. -->
                                    Current ORD Food Waste Research
                                </h4>
                                <p class="card-text">
                                    <!-- NOTE: This section is paragraph text in an event card's body. -->
                                    Last update 06-09-2020.
                                    <button class="btn btn-md btn-success float-right m-2"
                                            onclick="window.location.href='/support/files/Current ORD Food Waste Research - 06-09-2020.docx'">
                                        Download the document
                                    </button>
                                </p>
                            </div>
                        </div>
                        <div class="card-footer">
                            <!-- NOTE: This section is used to document when this event card was last updated. -->
                            <small class="text-muted">Last updated 6/15/2020</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 mt-3">
                    <div class="card">
                        <div class="card-horizontal">
                            <div class="img-square-wrapper card-horizontal-img col-2">
                                <!-- NOTE: Day of the week. -->
                                <div class="col-12">MON</div>
                                <!-- NOTE: Month and date. -->
                                <div class="col-12">July 20</div>
                                <!-- NOTE: Year. -->
                                <div class="col-12">2020</div>
                            </div>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <!-- NOTE: This section is the bolded title in an event card. -->
                                    Microplastics Project ORD -- Microsoft Teams Meeting
                                </h4>
                                <p class="card-text">
                                    <!-- NOTE: This section is paragraph text in an event card's body. -->
                                    First meeting discuss progress. <mark>Meetings begin every week 0830 Hrs. MS Teams.</mark>
                                    <button class="btn btn-md btn-success float-right m-2"
                                            onclick="window.location.href='https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWQzMzExNjctNDdhMy00ZTc0LWFhNTQtZGQ4ZTFkNGY4NjJl%40thread.v2/0?context=%7b%22Tid%22%3a%2288b378b3-6748-4867-acf9-76aacbeca6a7%22%2c%22Oid%22%3a%221b785807-e71d-456f-a25c-d3aa9129d28f%22%7d'">
                                        Join Meeting
                                    </button>
                                </p>
                            </div>
                        </div>
                        <div class="card-footer">
                            <!-- NOTE: This section is used to document when this event card was last updated. -->
                            <small class="text-muted">Last updated 7/21/2020</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 mt-3">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ADAM/support/templates/main/manual.html
{% extends "main/base.html" %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="white-box">
    <h3>ADAM Introduction</h3>
    <div>
        <p>TODO DESCRIPTION.</p>
    </div>
    <div>
        <div class="well">
            <h4>Quick links</h4>
            {#<div><a href="{% url 'citation' %}">Download Citations (txt)</a></div>#}
            <div><a href="{% url 'support:download_manual' %}">View the ADAM user manual</a></div>
            <div><a href="{% url 'dashboard' %}">Access the main dashboard</a></div>
        </div>
    </div>
</div>

{% endblock %}

ADAM/support/templates/main/no_edit.html
{% extends "base/site_base_support.html" %}
{% load humanize %}

{% block support_content %}

<h3>{{APP_NAME}} Help/Suggestions</h3>
<p>
    You are not currently authorized to edit suggestions submitted by others.
</p>
{% endblock %}

ADAM/support/templates/main/support.html
{% extends "base/site_base_support.html" %}
{% load humanize %}

{% block support_content %}

<h3>ADAM Help/Suggestions</h3>
<p>
    Select an option to request help or make a suggestion.
</p>
{% endblock %}